package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Carte generated by hbm2java
 */
@Entity
@Table(name = "CARTE", schema = "PROJETPOMPIER")
public class Carte implements java.io.Serializable {

	private BigDecimal id;
	private String nomPoint;
	private String latitude;
	private String longitude;
	private BigDecimal type;
	private BigDecimal statute;
	private Set<Connection> connections = new HashSet<Connection>(0);
	private Set<Mission> missions = new HashSet<Mission>(0);
	private Set<Equipe> equipes = new HashSet<Equipe>(0);

	public Carte() {
	}

	public Carte(BigDecimal id, String nomPoint, String latitude, String longitude, BigDecimal type,
			BigDecimal statute) {
		this.id = id;
		this.nomPoint = nomPoint;
		this.latitude = latitude;
		this.longitude = longitude;
		this.type = type;
		this.statute = statute;
	}

	public Carte(BigDecimal id, String nomPoint, String latitude, String longitude, BigDecimal type, BigDecimal statute,
			Set<Connection> connections, Set<Mission> missions, Set<Equipe> equipes) {
		this.id = id;
		this.nomPoint = nomPoint;
		this.latitude = latitude;
		this.longitude = longitude;
		this.type = type;
		this.statute = statute;
		this.connections = connections;
		this.missions = missions;
		this.equipes = equipes;
	}

	@Id

	@Column(name = "ID_", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NOM_POINT", nullable = false, length = 30)
	public String getNomPoint() {
		return this.nomPoint;
	}

	public void setNomPoint(String nomPoint) {
		this.nomPoint = nomPoint;
	}

	@Column(name = "LATITUDE", nullable = false, length = 30)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE", nullable = false, length = 30)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "TYPE_", nullable = false, precision = 22, scale = 0)
	public BigDecimal getType() {
		return this.type;
	}

	public void setType(BigDecimal type) {
		this.type = type;
	}

	@Column(name = "STATUTE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStatute() {
		return this.statute;
	}

	public void setStatute(BigDecimal statute) {
		this.statute = statute;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carte")
	public Set<Connection> getConnections() {
		return this.connections;
	}

	public void setConnections(Set<Connection> connections) {
		this.connections = connections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carte")
	public Set<Mission> getMissions() {
		return this.missions;
	}

	public void setMissions(Set<Mission> missions) {
		this.missions = missions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carte")
	public Set<Equipe> getEquipes() {
		return this.equipes;
	}

	public void setEquipes(Set<Equipe> equipes) {
		this.equipes = equipes;
	}

}
