package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Connection generated by hbm2java
 */
@Entity
@Table(name = "CONNECTION", schema = "PROJETPOMPIER")
public class Connection implements java.io.Serializable {

	private BigDecimal id;
	private Management management;
	private RescueSearch rescueSearch;
	private Medical medical;
	private Logistic logistic;
	private Profil profil;
	private Carte carte;
	private Mission mission;
	private String cleHash;
	private Boolean autorisation;
	private String email;

	public Connection() {
	}

	public Connection(BigDecimal id, Management management, RescueSearch rescueSearch, Medical medical,
			Logistic logistic, Profil profil, Carte carte, Mission mission, String cleHash, String email) {
		this.id = id;
		this.management = management;
		this.rescueSearch = rescueSearch;
		this.medical = medical;
		this.logistic = logistic;
		this.profil = profil;
		this.carte = carte;
		this.mission = mission;
		this.cleHash = cleHash;
		this.email = email;
	}

	public Connection(BigDecimal id, Management management, RescueSearch rescueSearch, Medical medical,
			Logistic logistic, Profil profil, Carte carte, Mission mission, String cleHash, Boolean autorisation,
			String email) {
		this.id = id;
		this.management = management;
		this.rescueSearch = rescueSearch;
		this.medical = medical;
		this.logistic = logistic;
		this.profil = profil;
		this.carte = carte;
		this.mission = mission;
		this.cleHash = cleHash;
		this.autorisation = autorisation;
		this.email = email;
	}

	@Id

	@Column(name = "ID_", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFIL_MANAGEMENT_ID", nullable = false)
	public Management getManagement() {
		return this.management;
	}

	public void setManagement(Management management) {
		this.management = management;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFIL_RESCUE_SEARCH_ID", nullable = false)
	public RescueSearch getRescueSearch() {
		return this.rescueSearch;
	}

	public void setRescueSearch(RescueSearch rescueSearch) {
		this.rescueSearch = rescueSearch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFIL_MEDICAL_ID", nullable = false)
	public Medical getMedical() {
		return this.medical;
	}

	public void setMedical(Medical medical) {
		this.medical = medical;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFIL_LOGISTIC_ID", nullable = false)
	public Logistic getLogistic() {
		return this.logistic;
	}

	public void setLogistic(Logistic logistic) {
		this.logistic = logistic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROFIL_ID", nullable = false)
	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MISSION_CARTE_ID", nullable = false)
	public Carte getCarte() {
		return this.carte;
	}

	public void setCarte(Carte carte) {
		this.carte = carte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MISSION_ID", nullable = false)
	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	@Column(name = "CLE_HASH", nullable = false, length = 200)
	public String getCleHash() {
		return this.cleHash;
	}

	public void setCleHash(String cleHash) {
		this.cleHash = cleHash;
	}

	@Column(name = "AUTORISATION", precision = 1, scale = 0)
	public Boolean getAutorisation() {
		return this.autorisation;
	}

	public void setAutorisation(Boolean autorisation) {
		this.autorisation = autorisation;
	}

	@Column(name = "EMAIL", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
