package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipe generated by hbm2java
 */
@Entity
@Table(name = "EQUIPE", schema = "PROJETPOMPIER")
public class Equipe implements java.io.Serializable {

	private BigDecimal id;
	private Carte carte;
	private Mission mission;
	private String type;
	private Set<Membres> membreses = new HashSet<Membres>(0);

	public Equipe() {
	}

	public Equipe(BigDecimal id, Carte carte, Mission mission, String type) {
		this.id = id;
		this.carte = carte;
		this.mission = mission;
		this.type = type;
	}

	public Equipe(BigDecimal id, Carte carte, Mission mission, String type, Set<Membres> membreses) {
		this.id = id;
		this.carte = carte;
		this.mission = mission;
		this.type = type;
		this.membreses = membreses;
	}

	@Id

	@Column(name = "ID_", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MISSION_CARTE_ID", nullable = false)
	public Carte getCarte() {
		return this.carte;
	}

	public void setCarte(Carte carte) {
		this.carte = carte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MISSION_ID", nullable = false)
	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	@Column(name = "TYPE_", nullable = false, length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipe")
	public Set<Membres> getMembreses() {
		return this.membreses;
	}

	public void setMembreses(Set<Membres> membreses) {
		this.membreses = membreses;
	}

}
