package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medical generated by hbm2java
 */
@Entity
@Table(name = "MEDICAL", schema = "PROJETPOMPIER")
public class Medical implements java.io.Serializable {

	private BigDecimal id;
	private String spe;
	private Set<Profil> profils = new HashSet<Profil>(0);
	private Set<Connection> connections = new HashSet<Connection>(0);

	public Medical() {
	}

	public Medical(BigDecimal id) {
		this.id = id;
	}

	public Medical(BigDecimal id, String spe, Set<Profil> profils, Set<Connection> connections) {
		this.id = id;
		this.spe = spe;
		this.profils = profils;
		this.connections = connections;
	}

	@Id

	@Column(name = "ID_", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "SPE", length = 30)
	public String getSpe() {
		return this.spe;
	}

	public void setSpe(String spe) {
		this.spe = spe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medical")
	public Set<Profil> getProfils() {
		return this.profils;
	}

	public void setProfils(Set<Profil> profils) {
		this.profils = profils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medical")
	public Set<Connection> getConnections() {
		return this.connections;
	}

	public void setConnections(Set<Connection> connections) {
		this.connections = connections;
	}

}
