package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Membres generated by hbm2java
 */
@Entity
@Table(name = "MEMBRES", schema = "PROJETPOMPIER")
public class Membres implements java.io.Serializable {

	private BigDecimal id;
	private Mission missionByEquipeMissionId;
	private Mission missionByEquipeMissionCarteId;
	private Equipe equipe;
	private String nom;
	private Date prenom;

	public Membres() {
	}

	public Membres(BigDecimal id, Mission missionByEquipeMissionId, Mission missionByEquipeMissionCarteId,
			Equipe equipe, String nom, Date prenom) {
		this.id = id;
		this.missionByEquipeMissionId = missionByEquipeMissionId;
		this.missionByEquipeMissionCarteId = missionByEquipeMissionCarteId;
		this.equipe = equipe;
		this.nom = nom;
		this.prenom = prenom;
	}

	@Id

	@Column(name = "ID_", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQUIPE_MISSION_ID", nullable = false)
	public Mission getMissionByEquipeMissionId() {
		return this.missionByEquipeMissionId;
	}

	public void setMissionByEquipeMissionId(Mission missionByEquipeMissionId) {
		this.missionByEquipeMissionId = missionByEquipeMissionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQUIPE_MISSION_CARTE_ID", nullable = false)
	public Mission getMissionByEquipeMissionCarteId() {
		return this.missionByEquipeMissionCarteId;
	}

	public void setMissionByEquipeMissionCarteId(Mission missionByEquipeMissionCarteId) {
		this.missionByEquipeMissionCarteId = missionByEquipeMissionCarteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQUIPE_ID", nullable = false)
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@Column(name = "NOM", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRENOM", nullable = false, length = 7)
	public Date getPrenom() {
		return this.prenom;
	}

	public void setPrenom(Date prenom) {
		this.prenom = prenom;
	}

}
