package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Mission generated by hbm2java
 */
@Entity
@Table(name = "MISSION")
public class Mission implements java.io.Serializable {

	private Long idMission;
	private String lieu;
	private String debut;
	private String fin;
	private short nbDePlaces;
	private Boolean flagFin;
	
	public Mission() {
	}

	public Mission(Long id, String lieu, String debut, String fin, short nbDePlaces, Boolean flagFin) {
		this.idMission = id;
		this.lieu = lieu;
		this.debut = debut;
		this.fin = fin;
		this.nbDePlaces = nbDePlaces;
	}

	@Id

	@Column(name = "IDMISSION", unique = true, nullable = false, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="MISSION_gen_seq")
    @SequenceGenerator(name="MISSION_gen_seq", sequenceName="MISSION_SEQ", allocationSize=1)
	public Long getId() {
		return this.idMission;
	}

	public void setId(Long id) {
		this.idMission = id;
	}

	@Column(name = "LIEU", nullable = false, length = 30)
	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	@Column(name = "DEBUT", nullable = false, length = 7)
	public String getDebut() {
		return this.debut;
	}

	public void setDebut(String debut) {
		this.debut = debut;
	}
	
	@Column(name = "FIN", nullable = false, length = 7)
	public String getFin() {
		return this.fin;
	}

	public void setFin(String fin) {
		this.fin = fin;
	}

	@Column(name = "NB_DE_PLACES", nullable = false, precision = 3, scale = 0)
	public short getNbDePlaces() {
		return this.nbDePlaces;
	}

	public void setNbDePlaces(short nbDePlaces) {
		this.nbDePlaces = nbDePlaces;
	}

	@Column(name = "FLAG_FIN", precision = 1, scale = 0)
	public Boolean getFlagFin() {
		return this.flagFin;
	}

	public void setFlagFin(Boolean flagFin) {
		this.flagFin = flagFin;
	}

}
