package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mission generated by hbm2java
 */
@Entity
@Table(name = "MISSION")
public class Mission implements java.io.Serializable {

	private Long id;
	private Carte carte;
	private String lieu;
	private String debut;
	private String fin;
	private short nbDePlaces;
	private Boolean flagFin;
	private Set<Membres> membresesForEquipeMissionId = new HashSet<Membres>(0);
	private Set<Equipe> equipes = new HashSet<Equipe>(0);
	private Set<Membres> membresesForEquipeMissionCarteId = new HashSet<Membres>(0);
	private Set<Connection> connections = new HashSet<Connection>(0);

	public Mission() {
	}

	public Mission(Long id, Carte carte, String lieu, String debut, String fin, short nbDePlaces) {
		this.id = id;
		this.carte = carte;
		this.lieu = lieu;
		this.debut = debut;
		this.fin = fin;
		this.nbDePlaces = nbDePlaces;
	}

	public Mission(Long id, Carte carte, String lieu, String debut, String fin, short nbDePlaces, Boolean flagFin,
			Set<Membres> membresesForEquipeMissionId, Set<Equipe> equipes,
			Set<Membres> membresesForEquipeMissionCarteId, Set<Connection> connections) {
		this.id = id;
		this.carte = carte;
		this.lieu = lieu;
		this.debut = debut;
		this.fin = fin;
		this.nbDePlaces = nbDePlaces;
		this.flagFin = flagFin;
		this.membresesForEquipeMissionId = membresesForEquipeMissionId;
		this.equipes = equipes;
		this.membresesForEquipeMissionCarteId = membresesForEquipeMissionCarteId;
		this.connections = connections;
	}

	@Id

	@Column(name = "ID_", unique = true, nullable = false, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="MISSION_gen_seq")
    @SequenceGenerator(name="MISSION_gen_seq", sequenceName="MISSION_SEQ", allocationSize=1)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARTE_ID", nullable = false)
	public Carte getCarte() {
		return this.carte;
	}

	public void setCarte(Carte carte) {
		this.carte = carte;
	}

	@Column(name = "LIEU", nullable = false, length = 30)
	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	@Column(name = "DEBUT", nullable = false, length = 7)
	public String getDebut() {
		return this.debut;
	}

	public void setDebut(String debut) {
		this.debut = debut;
	}
	
	@Column(name = "FIN", nullable = false, length = 7)
	public String getFin() {
		return this.fin;
	}

	public void setFin(String fin) {
		this.fin = fin;
	}

	@Column(name = "NB_DE_PLACES", nullable = false, precision = 3, scale = 0)
	public short getNbDePlaces() {
		return this.nbDePlaces;
	}

	public void setNbDePlaces(short nbDePlaces) {
		this.nbDePlaces = nbDePlaces;
	}

	@Column(name = "FLAG_FIN", precision = 1, scale = 0)
	public Boolean getFlagFin() {
		return this.flagFin;
	}

	public void setFlagFin(Boolean flagFin) {
		this.flagFin = flagFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "missionByEquipeMissionId")
	public Set<Membres> getMembresesForEquipeMissionId() {
		return this.membresesForEquipeMissionId;
	}

	public void setMembresesForEquipeMissionId(Set<Membres> membresesForEquipeMissionId) {
		this.membresesForEquipeMissionId = membresesForEquipeMissionId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mission")
	public Set<Equipe> getEquipes() {
		return this.equipes;
	}

	public void setEquipes(Set<Equipe> equipes) {
		this.equipes = equipes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "missionByEquipeMissionCarteId")
	public Set<Membres> getMembresesForEquipeMissionCarteId() {
		return this.membresesForEquipeMissionCarteId;
	}

	public void setMembresesForEquipeMissionCarteId(Set<Membres> membresesForEquipeMissionCarteId) {
		this.membresesForEquipeMissionCarteId = membresesForEquipeMissionCarteId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mission")
	public Set<Connection> getConnections() {
		return this.connections;
	}

	public void setConnections(Set<Connection> connections) {
		this.connections = connections;
	}

}
