package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parametre generated by hbm2java
 */
@Entity
@Table(name = "PARAMETRE", schema = "PROJETPOMPIER")
public class Parametre implements java.io.Serializable {

	private BigDecimal id;
	private Boolean modeNuit;
	private Boolean notificationMail;

	public Parametre() {
	}

	public Parametre(BigDecimal id) {
		this.id = id;
	}

	public Parametre(BigDecimal id, Boolean modeNuit, Boolean notificationMail) {
		this.id = id;
		this.modeNuit = modeNuit;
		this.notificationMail = notificationMail;
	}

	@Id

	@Column(name = "ID_", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "MODE_NUIT", precision = 1, scale = 0)
	public Boolean getModeNuit() {
		return this.modeNuit;
	}

	public void setModeNuit(Boolean modeNuit) {
		this.modeNuit = modeNuit;
	}

	@Column(name = "NOTIFICATION_MAIL", precision = 1, scale = 0)
	public Boolean getNotificationMail() {
		return this.notificationMail;
	}

	public void setNotificationMail(Boolean notificationMail) {
		this.notificationMail = notificationMail;
	}

}
