package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "PROFIL")
public class Profil implements java.io.Serializable {

	private Long id;
	private String nom;
	private String prenom;
	private String numeroDeTelephone;
	private String role;
	private Date dateDeNaissance;

	public Profil() {
	}

	public Profil(Long id, String nom, String prenom, String numeroDeTelephone, String role, 
			Date dateDeNaissance) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.numeroDeTelephone = numeroDeTelephone;
		this.role = role;
		this.dateDeNaissance = dateDeNaissance;
	}

	@Id

	@Column(name = "ID_", unique = true, nullable = false, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="PROFIL_gen_seq")
    @SequenceGenerator(name="PROFIL_gen_seq", sequenceName="PROFIL_SEQ", allocationSize=1)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	@Column(name = "NOM", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "NUMERO_DE_TELEPHONE", nullable = false, length = 10)
	public String getNumeroDeTelephone() {
		return this.numeroDeTelephone;
	}

	public void setNumeroDeTelephone(String numeroDeTelephone) {
		this.numeroDeTelephone = numeroDeTelephone;
	}

	@Column(name = "ROLE_", nullable = false, length = 30)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DE_NAISSANCE", length = 7)
	public Date getDateDeNaissance() {
		return this.dateDeNaissance;
	}

	public void setDateDeNaissance(Date dateDeNaissance) {
		this.dateDeNaissance = dateDeNaissance;
	}

}
