package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "PROFIL")
public class Profil implements java.io.Serializable {

	private Long idPompier;
	private String email;
	private String mdp;
	private String nom;
	private String prenom;
	private String numeroDeTelephone;
	private String dateDeNaissance;
	private String matricule;
	private int administrateur;
	private int enMission;


	public Profil() {
	}

	public Profil(Long id, String email, String mdp, String nom, String prenom, String numeroDeTelephone,
			String dateDeNaissance, String matricule, int administrateur, int enMission) {
		this.idPompier = id;
		this.email = email;
		this.mdp = mdp;
		this.nom = nom;
		this.prenom = prenom;
		this.numeroDeTelephone = numeroDeTelephone;
		this.dateDeNaissance = dateDeNaissance;
		this.matricule = matricule;
		this.administrateur = administrateur;
		this.enMission = enMission;
	}

	@Id

	@Column(name = "IDPOMPIER", unique = true, nullable = false, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="PROFIL_gen_seq")
    @SequenceGenerator(name="PROFIL_gen_seq", sequenceName="PROFIL_SEQ", allocationSize=1)
	public Long getId() {
		return this.idPompier;
	}

	public void setId(Long id) {
		this.idPompier = id;
	}


	@Column(name = "NOM", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "NUMERO_DE_TELEPHONE", nullable = false, length = 10)
	public String getNumeroDeTelephone() {
		return this.numeroDeTelephone;
	}

	public void setNumeroDeTelephone(String numeroDeTelephone) {
		this.numeroDeTelephone = numeroDeTelephone;
	}

	@Column(name = "DATE_DE_NAISSANCE", length = 30)
	public String getDateDeNaissance() {
		return this.dateDeNaissance;
	}

	public void setDateDeNaissance(String dateDeNaissance) {
		this.dateDeNaissance = dateDeNaissance;
	}
	
	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MDP", length = 30)
	public String getMdp() {
		return mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@Column( name = "MATRICULE", length = 15)
	public String getMatricule() {
		return matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column( name = "ADMINISTRATEUR")
	public int getAdmin() {
		return administrateur;
	}

	public void setAdmin(int admin) {
		this.administrateur = admin;
	}
	
	@Column( name = "ENMISSION")
	public int getEnMission() {
		return enMission;
	}

	public void setEnMission(int enMission) {
		this.enMission = enMission;
	}



}
