package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "PROFIL", schema = "PROJETPOMPIER")
public class Profil implements java.io.Serializable {

	private BigDecimal id;
	private Management management;
	private RescueSearch rescueSearch;
	private Medical medical;
	private Logistic logistic;
	private String nom;
	private String prenom;
	private String numeroDeTelephone;
	private String role;
	private Date dateDeNaissance;
	private Set<Connection> connections = new HashSet<Connection>(0);

	public Profil() {
	}

	public Profil(BigDecimal id, Management management, RescueSearch rescueSearch, Medical medical, Logistic logistic,
			String nom, String prenom, String numeroDeTelephone, String role) {
		this.id = id;
		this.management = management;
		this.rescueSearch = rescueSearch;
		this.medical = medical;
		this.logistic = logistic;
		this.nom = nom;
		this.prenom = prenom;
		this.numeroDeTelephone = numeroDeTelephone;
		this.role = role;
	}

	public Profil(BigDecimal id, Management management, RescueSearch rescueSearch, Medical medical, Logistic logistic,
			String nom, String prenom, String numeroDeTelephone, String role, Date dateDeNaissance,
			Set<Connection> connections) {
		this.id = id;
		this.management = management;
		this.rescueSearch = rescueSearch;
		this.medical = medical;
		this.logistic = logistic;
		this.nom = nom;
		this.prenom = prenom;
		this.numeroDeTelephone = numeroDeTelephone;
		this.role = role;
		this.dateDeNaissance = dateDeNaissance;
		this.connections = connections;
	}

	@Id

	@Column(name = "ID_", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGEMENT_ID", nullable = false)
	public Management getManagement() {
		return this.management;
	}

	public void setManagement(Management management) {
		this.management = management;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESCUE_SEARCH_ID", nullable = false)
	public RescueSearch getRescueSearch() {
		return this.rescueSearch;
	}

	public void setRescueSearch(RescueSearch rescueSearch) {
		this.rescueSearch = rescueSearch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MEDICAL_ID", nullable = false)
	public Medical getMedical() {
		return this.medical;
	}

	public void setMedical(Medical medical) {
		this.medical = medical;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOGISTIC_ID", nullable = false)
	public Logistic getLogistic() {
		return this.logistic;
	}

	public void setLogistic(Logistic logistic) {
		this.logistic = logistic;
	}

	@Column(name = "NOM", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "NUMERO_DE_TELEPHONE", nullable = false, length = 10)
	public String getNumeroDeTelephone() {
		return this.numeroDeTelephone;
	}

	public void setNumeroDeTelephone(String numeroDeTelephone) {
		this.numeroDeTelephone = numeroDeTelephone;
	}

	@Column(name = "ROLE_", nullable = false, length = 30)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DE_NAISSANCE", length = 7)
	public Date getDateDeNaissance() {
		return this.dateDeNaissance;
	}

	public void setDateDeNaissance(Date dateDeNaissance) {
		this.dateDeNaissance = dateDeNaissance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profil")
	public Set<Connection> getConnections() {
		return this.connections;
	}

	public void setConnections(Set<Connection> connections) {
		this.connections = connections;
	}

}
