package com.cergy.eisti.projet_INSARAG.model;
// Generated 11-Dec-2018 14:29:04 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR")
public class Utilisateur implements java.io.Serializable {

	private Long id;
	private String email;
	private String mdp;
	@Transient
	private String confirmationMdp;
	private String nom;
	private String prenom;
	private String telephone;
	private String naissance;
	private String matricule;
	private int autorisation;
	private int enMission;
	private int role;

	public Utilisateur() {
	}

	public Utilisateur(Long id, String email, String mdp, String nom, String prenom, String telephone, String naissance, String matricule,
			int autorisation, int enMission, int role) {
		this.id = id;
		this.email = email;
		this.mdp = mdp;
		this.nom = nom;
		this.prenom = prenom;
		this.telephone = telephone;
		this.naissance = naissance;
		this.matricule = matricule;
		this.autorisation = autorisation;
		this.enMission = enMission;
		this.role = role;
	}

	@Id

	@Column(name = "IDUTILISATEUR", unique = true, nullable = false, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="UTILISATEUR_gen_seq")
    @SequenceGenerator(name="UTILISATEUR_gen_seq", sequenceName="UTILISATEUR_SEQ", allocationSize=1)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "EMAIL", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "MDP", nullable = false, length = 30)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@Transient
	public String getConfirmationMdp() {
		return confirmationMdp;
	}

	public void setConfirmationMdp(String confirmationMdp) {
		this.confirmationMdp = confirmationMdp;
	}

	@Column(name = "NOM", nullable = false, length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "NUMERO_DE_TELEPHONE", nullable = false, length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	//@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DE_NAISSANCE", length = 7)
	public String getNaissance() {
		return this.naissance;
	}

	public void setNaissance(String naissance) {
		this.naissance = naissance;
	}
	
	@Column(name = "MATRICULE", nullable = false, length = 30)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}
	
	@Column(name = "ADMINISTRATEUR", nullable = false, length = 30)
	public int getAutorisation() {
		return this.autorisation;
	}

	public void setAutorisation(int autorisation) {
		this.autorisation = autorisation;
	}
	
	@Column(name = "ENMISSION", nullable = false, length = 30)
	public int getEnMission() {
		return this.enMission;
	}

	public void setEnMission(int enMission) {
		this.enMission = enMission;
	}
	
	@Column(name = "ROLE", nullable = false, length = 30)
	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

}
